### PR TITLE
Make 'Download Certificate' string translatable

### PR DESCRIPTION
**Pull request by MarcGuay**

### CODE REVIEW

**Comment by MarcGuay** [comment]
This doesn't actually seem to work for some reason, always displays the default text even if a translation is available....

**Comment by fpcorso** [comment]
Hey @MarcGuay . Thanks for the pull request! This should work how you modified it. I wonder if the newer translation system going through w.org requires the code in their repository to have this change before it is reflected correctly? I'll get this merged shortly,

**Comment by MarcGuay** [comment]
It doesn't work for me.  gettext functions __() and _e() don't work via admin-ajax.php.

**Comment by fpcorso** [comment]
Since we are moving the certificate feature to its own addon and will be updating it shortly to allow admins to customize the download certificate text, I am not going to get this string added to the translation files for the core plugin as the string will be removed soon anyways.

**Pull request closed without merging**
